# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sign_data_pb2 as sign__data__pb2


class StreamDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.biDirectionalStream = channel.unary_unary(
                '/signData.StreamDataService/biDirectionalStream',
                request_serializer=sign__data__pb2.RequestMessage.SerializeToString,
                response_deserializer=sign__data__pb2.ResponseMessage.FromString,
                )


class StreamDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def biDirectionalStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'biDirectionalStream': grpc.unary_unary_rpc_method_handler(
                    servicer.biDirectionalStream,
                    request_deserializer=sign__data__pb2.RequestMessage.FromString,
                    response_serializer=sign__data__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signData.StreamDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def biDirectionalStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signData.StreamDataService/biDirectionalStream',
            sign__data__pb2.RequestMessage.SerializeToString,
            sign__data__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
