version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "80:80"
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    lstm:
      build: ./lstm
      ports:
        - "50051:50051"
      nlp:
        build: ./nlp
        ports:
          - "50052:50052"
 
volumes:
  snoopy:
