# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sign_data_nlp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sign_data_nlp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sign_data_nlp.proto\x12\x0bsignDataNLP\"\x1e\n\x0eRequestMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\x0fResponseMessage\x12\r\n\x05reply\x18\x01 \x01(\t2e\n\x11StreamDataService\x12P\n\x13\x62iDirectionalStream\x12\x1b.signDataNLP.RequestMessage\x1a\x1c.signDataNLP.ResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sign_data_nlp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=36
  _globals['_REQUESTMESSAGE']._serialized_end=66
  _globals['_RESPONSEMESSAGE']._serialized_start=68
  _globals['_RESPONSEMESSAGE']._serialized_end=100
  _globals['_STREAMDATASERVICE']._serialized_start=102
  _globals['_STREAMDATASERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
