# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sign_data_lstm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sign_data_lstm.proto\x12\x0csignDataLSTM\"\x19\n\x07Gesture\x12\x0e\n\x06points\x18\x01 \x03(\x02\"5\n\x0eRequestMessage\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.signDataLSTM.Gesture\" \n\x0fResponseMessage\x12\r\n\x05reply\x18\x01 \x01(\t2g\n\x11StreamDataService\x12R\n\x13\x62iDirectionalStream\x12\x1c.signDataLSTM.RequestMessage\x1a\x1d.signDataLSTM.ResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sign_data_lstm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GESTURE']._serialized_start=38
  _globals['_GESTURE']._serialized_end=63
  _globals['_REQUESTMESSAGE']._serialized_start=65
  _globals['_REQUESTMESSAGE']._serialized_end=118
  _globals['_RESPONSEMESSAGE']._serialized_start=120
  _globals['_RESPONSEMESSAGE']._serialized_end=152
  _globals['_STREAMDATASERVICE']._serialized_start=154
  _globals['_STREAMDATASERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
